<a href="https://colab.research.google.com/github/zebsoftware/Machine-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr= np.array([
                  [1,2,3,4,5],
                  [2,3,4,5,6],
                  [3,4,5,6,7],
                  [4,5,6,7,8]


                  ] ,dtype="int16")
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [ ]:
arr.ndim
arr.shape
arr.dtype
arr.itemsize
arr.size
arr.nbytes

40

In [ ]:
# creating 3d array
page1 = np.array([
     [
      [1,2,3,4],
      [4,5,6,7],

         ],
       [
      [0,0,7,0],
      [0,0,0,0]
         ],
       [
      [1,2,3,4],
      [4,5,6,7]
         ],

 ])
# page1= page1+2

page1.ndim

#  page1.shape
# indexing 3d dimensional array
print(page1[2][1][3])
print(page1[0,0,3]+page1[1,0,2])

7
4


In [ ]:
# slicing in numpy


slice = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6],
    [3,4,5,6,7],
    [4,5,6,7,8]
])



#  ROWS SLICING
# print(slice[0:4]) this will print the whole array because the last index is exclusive
# print(slice[0:3])  this will print the first 3 rows
# print(slice[0:4:2])  this will print every second row  the 2 is the indication for printing the second after the first rows is selected
# print(slice[0:4:1])  all row again
# print(slice[::-1])    print array in reverse order
# print(slice[::-2])    print the array in reverse with every second rows after the first



# columns slicing
# print(slice[:,0])
# print(slice[:,1])
# print(slice[:,2])
# print(slice[:,-1]) all these print the columns of each rows
# print(slice[:,-1])

# print(slice[:,0:4])
# print(slice[:,0:5:2])


# slice[1,1:5:2]

slice[::2,2]


array([3, 5])