<a href="https://colab.research.google.com/github/zebsoftware/Machine-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr= np.array([
                  [1,2,3,4,5],
                  [2,3,4,5,6],
                  [3,4,5,6,7],
                  [4,5,6,7,8]


                  ] )
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [3]:
arr.ndim
arr.shape

(4, 5)

In [29]:
# creating 3d array
page1 = np.array([
     [
      [1,2,3,4],
      [4,5,6,7],

         ],
       [
      [0,0,7,0],
      [0,0,0,0]
         ],
       [
      [1,2,3,4],
      [4,5,6,7]
         ],

 ])
# page1= page1+2

page1.ndim

#  page1.shape
# indexing 3d dimensional array
print(page1[2][1][3])
print(page1[0,0,3]+page1[1,0,2])

7
4
