<a href="https://colab.research.google.com/github/zebsoftware/Machine-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.array([1,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [2]:

arr = np.array([[1,2,3],[2,3,4],[4,5,6]])

# arr = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[6,7,8]]],dtype=float)
# arr = np.array([[[1,2,3],[2,3,4]],[[4,5,6],[6,7,8]]],dtype=bool)
# arr = np.arange(1,11).reshape(5,2)
# arr = np.arange(1,11,2)
# arr = np.random.random((1,11))
# arr = np.linspace(-10,10,10)
# print(arr)
# arr.ndim
# print(arr.shape)
# print(arr.size)
# arr.itemsize

# arr= arr.astype(float)
# arr= arr.astype(np.int32)
# arr *5
# arr **5 raise every element to the power of 5
# arr +5
# arr > 3

# arr < 3
# arr == 3
arr1 = np.array([[1,2,3],[2,3,4],[5,8,9]])
# arr * arr1
# arr + arr1
# arr=arr/arr1
# arr.astype(int)

In [3]:

arr = np.random.randint(1,100,(3,3))
# arr1= np.array([[1,2,3],[2,3,4],[5,8,9]])
arr



array([[49, 99, 53],
       [52, 54, 97],
       [51, 23, 50]])

In [4]:
np.min(arr)
np.max(arr)
np.sum(arr)
np.prod(arr)

np.int64(4107182476597200)

In [5]:
# taking the min and max value in each col and row axis is 0 for col and 1 for row
np.min(arr,axis=0)
np.max(arr,axis=1)
np.sum(arr,axis=1)

array([201, 203, 124])

In [6]:
np.mean(arr).astype(int)

np.int64(58)

In [7]:
np.median(arr).astype(int)

np.int64(52)

In [8]:
np.std(arr)
np.var(arr)

np.float64(521.5555555555555)

In [9]:
np.sin(arr)
np.cos(arr)
np.tan(arr)

array([[ -3.17290855, -25.09253498,  -0.4311582 ],
       [ -6.05327238,   0.6738001 ,  -0.4103213 ],
       [  0.90308615,   1.58815308,  -0.27190061]])

In [10]:
print(arr)
print(arr1)

np.dot(arr,arr1)

[[49 99 53]
 [52 54 97]
 [51 23 50]]
[[1 2 3]
 [2 3 4]
 [5 8 9]]


array([[ 512,  819, 1020],
       [ 645, 1042, 1245],
       [ 347,  571,  695]])

In [11]:
np.log(arr)
# np.exp(arr)

array([[3.8918203 , 4.59511985, 3.97029191],
       [3.95124372, 3.98898405, 4.57471098],
       [3.93182563, 3.13549422, 3.91202301]])

In [12]:
np.round(np.log(arr))
np.floor(np.log(arr))
np.ceil(np.log(arr))

array([[4., 5., 4.],
       [4., 4., 5.],
       [4., 4., 4.]])

In [13]:
a1 = np.arange(1,11)
a2 = np.arange(1,13).reshape(3,4)
a3 = np.arange(1,13).reshape(2,3,2)
print(a1)

print(a2)

print(a3)


[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [14]:
a1[0]
a1[-1]

np.int64(10)

In [15]:
a2[1,2]
a2[1,0]

np.int64(5)

In [16]:
a3
a3[1,0,0]
a3[0,2,0]


np.int64(5)

In [17]:
a1[2:5]
a1[1:8:2]

array([2, 4, 6, 8])

In [18]:
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a2[0,:]
a2[0:3:2,2]


array([ 3, 11])

In [28]:
a2[1:,1:3]
a2[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [27]:
a2[0:3:2,0:4:3]
a2[::2,::3]

array([[ 1,  4],
       [ 9, 12]])

In [29]:
a2[::2,1:4:2]

array([[ 2,  4],
       [10, 12]])

In [33]:
a3 =  np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [35]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [37]:
a3[::2]

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [38]:
a3[0,1,:]

array([3, 4, 5])

In [39]:
a3[1,:,1]

array([10, 13, 16])

In [40]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [41]:
a3[0::2,0,0:3:2]

array([[ 0,  2],
       [18, 20]])

In [43]:
a1
for i in a1:
    print(i)


1
2
3
4
5
6
7
8
9
10


In [44]:

for i in a2:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [45]:

for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [47]:
for i in np.nditer(a2):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
np.transpose(a2)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [51]:
np.ravel(a2)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [54]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

np.hstack((a4,a5))
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
a4
np.hsplit(a4,2)
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]